### ISSUE TITLE
將應用放在d盤導致的路徑錯誤 

### ISSUE THREAD

**Issue by 123hi123** [WEIFENG2333/VideoCaptioner#121]
### 问题描述 | Problem Description

因為c盤空間吃緊 所以放在d盤
路徑: D:\file\tool\VideoCaptioner
轉錄的時候會找不到檔案
推測是wav檔案放置的路徑與城市找尋的路徑不一致
以下是相关代码段，可能会产生涉及 `C:\Users\joego\AppData\Local\Temp\bk_asr\tmp3031raz3\audio.wav` 的消息：

1. [WhisperASR.py](https://github.com/WEIFENG2333/VideoCaptioner/blob/fde41a035c1cd388971ab241b0e7edf78491a341/app/core/bk_asr/WhisperASR.py#L28-L121)
   ```python
   temp_dir = Path(tempfile.gettempdir()) / "bk_asr"
   temp_dir.mkdir(parents=True, exist_ok=True)

   with tempfile.TemporaryDirectory(dir=temp_dir) as temp_path:
       temp_dir = Path(temp_path)
       wav_path = temp_dir / "audio.wav"
       shutil.copy2(self.audio_path, wav_path)
       # 构建基础命令参数列表
       whisper_params = [
           str(self.whisper_cpp_path),
           '-m', str(self.model_path),
           '-f', str(wav_path),
           '-l', self.language,
           '--output-srt'
       ]
       logger.info("完整命令行参数: %s", ' '.join(whisper_params))
   ```

2. [FasterWhisperASR.py](https://github.com/WEIFENG2333/VideoCaptioner/blob/fde41a035c1cd388971ab241b0e7edf78491a341/app/core/bk_asr/FasterWhisperASR.py#L113-L211)
   ```python
   temp_dir = Path(tempfile.gettempdir()) / "bk_asr"
   temp_dir.mkdir(parents=True, exist_ok=True)

   with tempfile.TemporaryDirectory(dir=temp_dir) as temp_path:
       temp_dir = Path(temp_path)
       wav_path = temp_dir / "audio.wav"
       output_path = wav_path.with_suffix(".srt")

       shutil.copy2(self.audio_path, wav_path)
       cmd = self._build_command(wav_path)
       logger.info("Faster Whisper 执行命令: %s", " ".join(cmd))
   ```

ai 生成。

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：2024-12-08 13:43:35.750791
开始转换音频
转换为音频执行命令: ffmpeg -i D:\file\大三上\計網\上課錄影\1127.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y D:\file\tool\VideoCaptioner\work-dir\1127\【Audio】1127.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl.exe -m large-v2 --print_progress --model_dir D:\file\tool\VideoCaptioner\AppData\models C:\Users\joego\AppData\Local\Temp\bk_asr\tmp3031raz3\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v3 --one_word 1
2024-12-08 13:43:38 - transcript_thread - ERROR - 转录过程中发生错误: [WinError 2] 系統找不到指定的檔案。
Traceback (most recent call last):
  File "D:\file\tool\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 171, in _run
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
```

**Comment by WEIFENG2333** [comment]
这是软件找不到faster-whisper-xxl。

重启软件或者安装新版本可用解决。
