### ISSUE TITLE
maximum recursion depth exceeded while calling a python object

### ISSUE THREAD

**Issue by Xiaozekun** [WEIFENG2333/VideoCaptioner#123]
### 问题描述 | Problem Description

尝试翻译一小时的电影时报错

### 日志信息（可选）| Logs (Optional)

```shell
===========字幕优化任务开始===========
时间：2024-12-08 22:53:33.225748
尝试使用自带的API配置
使用 gpt-4o-mini 作为LLM模型
正在字幕断句...
根据字数 10354，确定分段数: 21
开始并行处理每个分段...
从缓存中获取断句结果
分段的句子提取完成，共 64 句
从缓存中获取断句结果
从缓存中获取断句结果
分段的句子提取完成，共 66 句
从缓存中获取断句结果
从缓存中获取断句结果
分段的句子提取完成，共 90 句
分段的句子提取完成，共 69 句
2024-12-08 22:53:35 - subtitle_spliter - WARNING - 无法匹配句子: 初めまして!
分段的句子提取完成，共 82 句
2024-12-08 22:53:35 - subtitle_spliter - WARNING - 无法匹配句子: よろしくお願いします。
2024-12-08 22:53:35 - subtitle_spliter - WARNING - 无法匹配句子: 待って!
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: こんばんは。
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: これ誰?
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: え、やばいね。
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: ツボ押しです。
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: 失礼します。
从缓存中获取断句结果
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: OK!
分段的句子提取完成，共 40 句
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: ありがとうございます。
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: 罰ゲーム、執行完了です。
从缓存中获取断句结果
2024-12-08 22:53:36 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: 日tit 逆に海で拭く。
2024-12-08 22:53:36 - subtitle_spliter - WARNING - 无法匹配句子: 本当は?本当に?嘘を言う人いらない。
从缓存中获取断句结果
分段的句子提取完成，共 57 句
分段的句子提取完成，共 78 句
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: 続けて。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: やってみよう!はい。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: はい、腕立てしてもらって。本当に?
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: じゃあ、もうちょっと若く言っておけばよかった。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: いいらしいです。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: 今からあーやばすぎ!どうぞ、やってください。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: 実際どっちですか?実際22歳です。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: で、負けた方が罰ゲーム?
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: エロいけど、すごいな。
从缓存中获取断句结果
2024-12-08 22:53:37 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: やばい。頭がいいぞ、確かに。
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: ひゃー!ちょっと失礼しますね、ごめんなさい。
从缓存中获取断句结果
2024-12-08 22:53:37 - subtitle_spliter - WARNING - 无法匹配句子: お疲れ様でした。
分段的句子提取完成，共 61 句
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: え、ちょっと待って!やば!ちょっと待って!
分段的句子提取完成，共 81 句
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: え、じゃあ落としても、数打っちゃいいんですもんね。
2024-12-08 22:53:38 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: 暑いけど、暑い!暑いけど、暑い!
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: え?やばいやばい。
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: まだですか?
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: なんですか?騎乗員ってしますよね。
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: 後ろはもうちょっとああ、いいですよ。
2024-12-08 22:53:38 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: もう、少しですね。
2024-12-08 22:53:38 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:38 - subtitle_spliter - WARNING - 无法匹配句子: 替えの高級パンツ用意してますので。
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: え、すご!
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: 確かめるって何?
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: 確認大事なんで。
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: 早い!ちょっと待って!なんでそんな早いの?
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: これ、隣にいるのちょっと。
2024-12-08 22:53:39 - subtitle_spliter - WARNING - LLM处理失败，使用规则based方法进行分割: 未匹配句子数量超过阈值，处理终止
2024-12-08 22:53:39 - subtitle_spliter - WARNING - 无法匹配句子: なんで?ちょっと待って。
2024-12-08 22:53:39 - subtitle_optimization_thread - ERROR - 优化失败: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 628, in process_segment
    return process_by_llm(asr_data_part.segments, model=model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 587, in process_by_llm
    merged_segments = merge_segments_based_on_sentences(segments, sentences)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 174, in merge_segments_based_on_sentences
    raise SubtitleProcessError(f"未匹配句子数量超过阈值，处理终止")
app.core.subtitle_processor.spliter.SubtitleProcessError: 未匹配句子数量超过阈值，处理终止

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\thread\subtitle_optimization_thread.py", line 124, in run
    asr_data = merge_segments(asr_data, model=llm_model,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 634, in merge_segments
    processed_segments = list(executor.map(process_segment, asr_data_segments))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 631, in process_segment
    return process_by_rules(asr_data_part.segments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 561, in process_by_rules
    result_segments.extend(split_long_segment(group))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 985 more times]
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 223, in split_long_segment
    max_word_count = MAX_WORD_COUNT_CJK if is_mainly_cjk(merged_text) else MAX_WORD_COUNT_ENGLISH
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 201, in is_mainly_cjk
    cjk_count += len(re.findall(pattern, text))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 216, in findall
  File "re\__init__.py", line 274, in _compile
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by WEIFENG2333** [comment]
可以提供字幕文件吗

**Comment by WEIFENG2333** [comment]
主要也是你的api问题，api模型返回结果错误。

用的什么api?

**Comment by Xiaozekun** [comment]
> 主要也是你的api问题，api模型返回结果错误。
> 
> 用的什么api?

字幕已经删掉了，用的默认的fast whisper large v3 + gpt-4o-mini 关掉单字时间戳的选项就没有报这个错误了
