### ISSUE TITLE
1.2创建语音转录任务失败

### ISSUE THREAD

**Issue by Hazukiaoi** [WEIFENG2333/VideoCaptioner#125]
### 问题描述 | Problem Description

拖动文件进入窗口后创建语音转录任务失败

### 日志信息（可选）| Logs (Optional)

```shell
开始创建文件任务：C:/tmp/Unity6.mp4
获取视频信息执行命令: ffmpeg -i C:/tmp/Unity6.mp4
视频时长: 1107.86秒
执行命令: ffmpeg -ss 00:05:32.358 -i C:/tmp/Unity6.mp4 -vframes 1 -q:v 2 -y C:/Users/MyPC/AppData/Local/VideoCaptioner/work-dir/Unity6/thumbnail.jpg
2024-12-09 01:04:18 - create_task_thread - ERROR - 创建任务失败: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\VideoCaptioner\app\core\thread\create_task_thread.py", line 31, in run
    self.create_file_task(self.file_path)
  File "C:\Users\MyPC\AppData\Local\VideoCaptioner\app\core\thread\create_task_thread.py", line 67, in create_file_task
    whisper_type = f"-{cfg.whisper_api_model.value.value}-{cfg.transcribe_language.value.value}"
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```

**Comment by WEIFENG2333** [comment]
你使用的是whisper api接口吗？

**Comment by Hazukiaoi** [comment]
是的，用whisper api接口

**Comment by WEIFENG2333** [comment]
api接口这个版本有bug

**Comment by WEIFENG2333** [comment]
#136
