### ISSUE TITLE
压制硬字幕时无法应用已设置好的字幕样式

### ISSUE THREAD

**Issue by kehya-G** [WEIFENG2333/VideoCaptioner#132]
### 问题描述 | Problem Description

**不论如何设置压制出来的都是同一种白色字幕**

![Snipaste_2024-12-10_23-40-15](https://github.com/user-attachments/assets/f70cba2e-c7a8-4391-be8f-044965ff1c3d)

### 日志信息（可选）| Logs (Optional)

```shell
2024-12-11 00:21:09 - version_manager_thread - ERROR - Failed to fetch version info: HTTPSConnectionPool(host='vc.bkfeng.top', port=443): Max retries exceeded with url: /api/version (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028D2FD34110>: Failed to resolve 'vc.bkfeng.top' ([Errno 11004] getaddrinfo failed)"))
Traceback (most recent call last):
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000028D2FD34110>: Failed to resolve 'vc.bkfeng.top' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vc.bkfeng.top', port=443): Max retries exceeded with url: /api/version (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028D2FD34110>: Failed to resolve 'vc.bkfeng.top' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VideoCaptioner\VideoCaptioner\app\core\thread\version_manager_thread.py", line 53, in getLatestVersionInfo
    response = requests.get(url, timeout=30, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vc.bkfeng.top', port=443): Max retries exceeded with url: /api/version (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000028D2FD34110>: Failed to resolve 'vc.bkfeng.top' ([Errno 11004] getaddrinfo failed)"))
开始创建视频合成任务：D:/1111111111111/000.srt D:/1111111111111/0000.mp4
视频合成任务创建完成：Task(id=0, queued_at=datetime.datetime(2024, 12, 11, 0, 22, 30, 624595), started_at=datetime.datetime(2024, 12, 11, 0, 22, 30, 624595), completed_at=None, status=<Status.GENERATING: '生成视频中'>, fraction_downloaded=0.0, work_dir='D:\\1111111111111', file_path='D:\\1111111111111\\0000.mp4', url=None, source=<Source.FILE_IMPORT: '文件导入'>, original_language=None, target_language=None, video_info=None, audio_format='wav', audio_save_path=None, transcribe_model=<TranscribeModelEnum.JIANYING: 'J 接口'>, transcribe_language='en', use_asr_cache=True, need_word_time_stamp=False, original_subtitle_save_path=None, whisper_model=None, whisper_api_key=None, whisper_api_base=None, whisper_api_model=None, whisper_api_prompt=None, faster_whisper_model=None, faster_whisper_model_dir=None, faster_whisper_device='cuda', faster_whisper_vad_filter=True, faster_whisper_vad_threshold=0.5, faster_whisper_vad_method=<VadMethodEnum.SILERO_V3: 'silero_v3'>, faster_whisper_ff_mdx_kim2=False, faster_whisper_one_word=True, faster_whisper_prompt=None, base_url=None, api_key=None, llm_model=None, need_translate=False, need_optimize=False, result_subtitle_save_path='D:\\1111111111111\\000.srt', thread_num=10, batch_size=10, subtitle_layout=None, max_word_count_cjk=12, max_word_count_english=18, need_split=True, need_video=True, video_save_path='D:\\1111111111111\\【卡卡】0000.mp4', soft_subtitle=False, subtitle_style_srt=None)
开始创建视频合成任务：D:/1111111111111/000.srt D:/1111111111111/0000.mp4
视频合成任务创建完成：Task(id=0, queued_at=datetime.datetime(2024, 12, 11, 0, 22, 30, 624595), started_at=datetime.datetime(2024, 12, 11, 0, 22, 30, 624595), completed_at=None, status=<Status.GENERATING: '生成视频中'>, fraction_downloaded=0.0, work_dir='D:\\1111111111111', file_path='D:\\1111111111111\\0000.mp4', url=None, source=<Source.FILE_IMPORT: '文件导入'>, original_language=None, target_language=None, video_info=None, audio_format='wav', audio_save_path=None, transcribe_model=<TranscribeModelEnum.JIANYING: 'J 接口'>, transcribe_language='en', use_asr_cache=True, need_word_time_stamp=False, original_subtitle_save_path=None, whisper_model=None, whisper_api_key=None, whisper_api_base=None, whisper_api_model=None, whisper_api_prompt=None, faster_whisper_model=None, faster_whisper_model_dir=None, faster_whisper_device='cuda', faster_whisper_vad_filter=True, faster_whisper_vad_threshold=0.5, faster_whisper_vad_method=<VadMethodEnum.SILERO_V3: 'silero_v3'>, faster_whisper_ff_mdx_kim2=False, faster_whisper_one_word=True, faster_whisper_prompt=None, base_url=None, api_key=None, llm_model=None, need_translate=False, need_optimize=False, result_subtitle_save_path='D:\\1111111111111\\000.srt', thread_num=10, batch_size=10, subtitle_layout=None, max_word_count_cjk=12, max_word_count_english=18, need_split=True, need_video=True, video_save_path='D:\\1111111111111\\【卡卡】0000.mp4', soft_subtitle=False, subtitle_style_srt=None)

===========视频合成任务开始===========
时间：2024-12-11 00:22:30.625595
开始合成视频: D:\1111111111111\0000.mp4
使用硬字幕
检查CUDA是否可用
CUDA可用
使用CUDA加速
添加硬字幕执行命令: ffmpeg -hwaccel cuda -i D:\1111111111111\0000.mp4 -acodec copy -vcodec libx264 -preset medium -vf subtitles='C\:/Users/mytrust/AppData/Local/Temp/VideoCaptioner/temp_subtitle.ass' -y D:\1111111111111\【卡卡】0000.mp4
视频总时长: 27.46秒
视频合成完成
视频合成完成，保存路径: D:\1111111111111\【卡卡】0000.mp4
```

**Comment by WEIFENG2333** [comment]
你打开的是否是合成的视频 :

【卡卡】0000.mp4
视频总时长: 27.46秒

**Comment by kehya-G** [comment]
> 日志看着合成过程毫无问题。
> 
> 你确认打开查看的是否是合成的视频 : 【卡卡】0000.mp4

①打开的是【卡卡】0000.mp4
②找到原因了：我用的是srt格式的字幕，压出来就是那个样式
要先在这个软件里把srt格式另存为成ass格式，再拿来用于字幕压制就没有问题了
【请问一下，这个软件有使用指南\文档\手册吗】
![ASS](https://github.com/user-attachments/assets/8ee5a658-7e74-4f19-8659-88a93a577f2b)

**Comment by Gwwwww777** [comment]
转换成ASS格式之后字幕样式依旧不会改变啊

**Comment by Morugana-Alt** [comment]
我压制硬字幕时也不会更改字幕样式，我参照楼上的方法使用ass格式的字幕，但是会报错

![Image](https://github.com/user-attachments/assets/24181952-e35a-4306-8383-a5baee1a28a3)
