### ISSUE TITLE
這個地方的提示詞是幹嘛的 放上提示詞之後轉錄錯誤

### ISSUE THREAD

**Issue by 123hi123** [WEIFENG2333/VideoCaptioner#139]
### 问题描述 | Problem Description

![image](https://github.com/user-attachments/assets/318aef53-7160-4fb2-bdf8-184c5a1d2d9d)
我在這裏放了一個提示詞: 中文部分一律使用繁體中文
然後報錯了
報錯訊息可以看下面日志訊息

### 日志信息（可选）| Logs (Optional)

```shell
audio [audio ...]
2024-12-11 23:01:26 - faster_whisper - ERROR - faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
Faster Whisper 返回值: 2
2024-12-11 23:01:27 - faster_whisper - ERROR - Faster Whisper 错误: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
2024-12-11 23:01:27 - transcript_thread - ERROR - 转录过程中发生错误: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
Traceback (most recent call last):
  File "D:\file\tool\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
    raise RuntimeError(error_msg)
RuntimeError: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
```

**Comment by WEIFENG2333** [comment]
这个版本参数会冲突，现在暂时不要填就行。

**Comment by 123hi123** [comment]
確實
