### ISSUE TITLE
请问这个是什么问题（我将油管的视频链接放进去后提示这个错误）

### ISSUE THREAD

**Issue by wibur0620** [WEIFENG2333/VideoCaptioner#146]
### 问题描述 | Problem Description

我将油管的视频链接（无论是地址栏复制的链接还是分享按钮出来的链接）复制进软件后，点击运行。配置好模型等。然后过了一会儿出现这个错误提示框
![image](https://github.com/user-attachments/assets/937f5930-eb42-44ac-b1a2-11de1015984b)

### 日志信息（可选）| Logs (Optional)

```shell
===================
开始创建URL任务：https://www.youtube.com/live/mBhkD0iFf4w?si=VSpHMz-_RC1Joh1i
开始下载视频: https://www.youtube.com/live/mBhkD0iFf4w?si=VSpHMz-_RC1Joh1i
使用cookiefile: D:\gongju\VideoCaptioner\VideoCaptioner\AppData\cookies.txt
2024-12-13 19:02:43 - create_task_thread - ERROR - 创建任务失败: ERROR: [youtube] mBhkD0iFf4w: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2973, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] mBhkD0iFf4w: Requested format is not available. Use --list-formats for a list of available formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\gongju\VideoCaptioner\VideoCaptioner\app\core\thread\create_task_thread.py", line 33, in run
    self.create_url_task(self.file_path)
  File "D:\gongju\VideoCaptioner\VideoCaptioner\app\core\thread\create_task_thread.py", line 151, in create_url_task
    video_file_path, subtitle_file_path, thumbnail_file_path, info_dict = download(url, cfg.work_dir.value, self.progress_hook)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\app\core\thread\create_task_thread.py", line 489, in download
    info_dict = ydl.extract_info(url, download=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1614, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1643, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1091, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "D:\gongju\VideoCaptioner\VideoCaptioner\runtime\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1030, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] mBhkD0iFf4w: Requested format is not available. Use --list-formats for a list of available formats

=========================以上是历史日志=========================
```

**Comment by wibur0620** [comment]
我的网络能正常播放油管视频

**Comment by wibur0620** [comment]
我想问题出在cookies.txt文件，我不删除这个文件后，错误提示就跟你这边那个Cookie 配置说明中演示的错误一样，但是当我将cookies.txt配置文件放进去后，出现的错误就是这样的,
![image](https://github.com/user-attachments/assets/29edaf4e-1c74-48f2-b8b3-df3ea47eb707)
为此我嗨特地又重新去下载了Cookie 配置文件，问题依旧

**Comment by WEIFENG2333** [comment]
似乎是这种`live`这种格式不支持，你应该使用视频页面的格式：https://www.youtube.com/watch?v=mBhkD0iFf4w
