### ISSUE TITLE
有的视频转录失败，3分钟的英语动画

### ISSUE THREAD

**Issue by xylolx** [WEIFENG2333/VideoCaptioner#154]
### 问题描述 | Problem Description

Fasterwhisper largev3 模型 

批量转录大概3分钟一集的英语动画。同个目录下部分成功，其他的转录失败。失败了不会继续处理后面的任务，需要手动按取消，再点开始处理才能继续往下处理。后续版本能否让它失败了也继续处理剩下的那些任务。

然后把失败的视频重新批量也都是失败，在任务创建界面单个转录也不行。 只有放在语音转录界面可以，不过这时生成的是【原始字幕】，不是【卡卡】字幕。

### 日志信息（可选）| Logs (Optional)

```shell
===========任务开始===========
时间：2024-12-15 11:47:31.365265
开始转录

===========转录任务开始===========
时间：2024-12-15 11:47:31.366262
开始转换音频
转换为音频执行命令: ffmpeg -i K:\VideoCaptioner\1111\31糖小屋.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y K:\VideoCaptioner\work-dir\31糖小屋\【Audio】31糖小屋.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl.exe -m large-v3 --print_progress --model_dir K:\VideoCaptioner\AppData\models C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp4is7dw2b\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.20 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 48 --max_line_count 1 --max_comma 20 --max_comma_cent 50
Standalone Faster-Whisper-XXL r194.5 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Starting transcription on: C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp4is7dw2b\audio.wav
16% |  32/199 | 00:01<<00:10 | 16.28 audio seconds/s
33% |  65/199 | 00:03<<00:07 | 16.81 audio seconds/s
48% |  95/199 | 00:06<<00:07 | 14.11 audio seconds/s
62% | 124/199 | 00:09<<00:05 | 13.34 audio seconds/s
76% | 151/199 | 00:11<<00:03 | 12.75 audio seconds/s
89% | 177/199 | 00:14<<00:01 | 12.64 audio seconds/s
99% | 198/199 | 00:16<<00:00 | 11.97 audio seconds/s
99% | 198/199 | 00:16<<00:00 | 11.97 audio seconds/s
Transcription speed: 11.77 audio seconds/s
Subtitles are written to 'C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp4is7dw2b' directory.
Operation finished in:  0:00:22.099
Faster Whisper 返回值: 0
2024-12-15 11:47:55 - faster_whisper - ERROR - Faster Whisper 错误: 
2024-12-15 11:47:55 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "K:\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
    raise RuntimeError(error_msg)
RuntimeError
2024-12-15 11:47:55 - subtitle_pipeline_thread - ERROR - pipeline 发生错误: 
转录过程中发生错误，终止流程

===========任务开始===========
时间：2024-12-15 11:48:37.826283
开始转录

===========转录任务开始===========
时间：2024-12-15 11:48:37.827280
开始转换音频
转换为音频执行命令: ffmpeg -i K:\VideoCaptioner\1111\33下雪天.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y K:\VideoCaptioner\work-dir\33下雪天\【Audio】33下雪天.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl.exe -m large-v3 --print_progress --model_dir K:\VideoCaptioner\AppData\models C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp_hz6oaj6\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.20 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 48 --max_line_count 1 --max_comma 20 --max_comma_cent 50
Standalone Faster-Whisper-XXL r194.5 running on: CUDA
Note: 'large-v3' model may produce worse results than 'large-v2'!
Starting transcription on: C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp_hz6oaj6\audio.wav
20% |  39/199 | 00:02<<00:08 | 18.34 audio seconds/s
36% |  71/199 | 00:03<<00:06 | 19.03 audio seconds/s
53% | 105/199 | 00:06<<00:05 | 17.37 audio seconds/s
66% | 131/199 | 00:08<<00:04 | 15.36 audio seconds/s
80% | 160/199 | 00:17<<00:04 |  9.39 audio seconds/s
92% | 183/199 | 00:19<<00:01 |  9.30 audio seconds/s
99% | 198/199 | 00:20<<00:00 |  9.51 audio seconds/s
99% | 198/199 | 00:20<<00:00 |  9.51 audio seconds/s
Transcription speed: 9.41 audio seconds/s
Subtitles are written to 'C:\Users\ADMINI~1\AppData\Local\Temp\bk_asr\tmp_hz6oaj6' directory.
Operation finished in:  0:00:26.351
Faster Whisper 返回值: 3221226505
2024-12-15 11:49:09 - faster_whisper - ERROR - Faster Whisper 错误: 
2024-12-15 11:49:09 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "K:\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
    raise RuntimeError(error_msg)
RuntimeError
2024-12-15 11:49:09 - subtitle_pipeline_thread - ERROR - pipeline 发生错误: 
转录过程中发生错误，终止流程

=========================以上是历史日志=========================
```

**Comment by xylolx** [comment]
> 这两个视频在单独的转录页面也会失败吗？
> 
> 是的话方面发一下视频吗，有可能一些视频没有适配，如果你发我可以帮助我排查。

批量和单独的结果是一样的，批量失败的话，放到单独的任务创建界面和语音转录的界面单独都会失败。

现在我把这两个失败的MP4视频又转成MP3去转录其中一个可以成功，另一个不行。

视频和MP3已上传到这。https://wwiu.lanzouu.com/iqDme2ibof1c

**Comment by WEIFENG2333** [comment]
可能当前完成处理条件过于严格，一些视频有问题。下版本将修复。

我问这里使用faster-Whisper没问题的，目前你可以你试试其他模型。
