### ISSUE TITLE
有个视频怎么都转录不了

### ISSUE THREAD

**Issue by Yukikaze1945** [WEIFENG2333/VideoCaptioner#164]
### 问题描述 | Problem Description

说是字符编码问题引起的
![image](https://github.com/user-attachments/assets/a29d18fa-7a0d-4d66-93e8-bfae8ee4bdf2)

### 日志信息（可选）| Logs (Optional)

```shell
===========任务开始===========
时间：2024-12-17 01:35:44.398347
开始转录

===========转录任务开始===========
时间：2024-12-17 01:35:44.481046
开始转换音频
转换为音频执行命令: ffmpeg -i D:\录播\生肉\メンバー限定のお絵描き作業配信.mkv -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y D:\VideoCaptioner\work-dir\メンバー限定のお絵描き作業配信\【Audio】メンバー限定のお絵描き作業配信.wav
开始语音转录
找到模型文件: D:\VideoCaptioner\AppData\models\ggml-large-v2.bin
完整命令行参数: whisper-cpp -m D:\VideoCaptioner\AppData\models\ggml-large-v2.bin -f C:\Users\18392\AppData\Local\Temp\bk_asr\tmpj7ivbs4w\audio.wav -l ja --output-srt
音频总时长: 5254 秒
2024-12-17 01:37:23 - whisper_asr - ERROR - 处理失败
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\bk_asr\WhisperASR.py", line 114, in _run
    line = self.process.stdout.readline()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 4119: invalid continuation byte
2024-12-17 01:37:24 - transcript_thread - ERROR - 转录过程中发生错误: 生成 SRT 文件失败: 'utf-8' codec can't decode byte 0xd7 in position 4119: invalid continuation byte
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\bk_asr\WhisperASR.py", line 114, in _run
    line = self.process.stdout.readline()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 4119: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\WhisperASR.py", line 145, in _run
    raise RuntimeError(f"生成 SRT 文件失败: {str(e)}")
RuntimeError: 生成 SRT 文件失败: 'utf-8' codec can't decode byte 0xd7 in position 4119: invalid continuation byte
2024-12-17 01:37:25 - subtitle_pipeline_thread - ERROR - pipeline 发生错误: 生成 SRT 文件失败: 'utf-8' codec can't decode byte 0xd7 in position 4119: invalid continuation byte
转录过程中发生错误，终止流程

===========任务开始===========
时间：2024-12-17 01:37:26.029583
开始转录
```

**Comment by asp3000** [comment]
你把【メンバー限定のお絵描き作業配信.mkv】 这个文件名改为纯英文的试下？

**Comment by WEIFENG2333** [comment]
使用FasterWhisper 应该可以解决
