### ISSUE TITLE
翻译和优化字幕时提示调用Python时超出最大递归深度

### ISSUE THREAD

**Issue by JockeyW** [WEIFENG2333/VideoCaptioner#179]
### 问题描述 | Problem Description

如图，这是因为字幕太长了吗，影片大概两小时+
![error](https://github.com/user-attachments/assets/c70d9fb0-9e1a-497d-b8b2-0da45048f107)

### 日志信息（可选）| Logs (Optional)

```shell
2024-12-20 17:17:37 - subtitle_optimization_thread - ERROR - 优化失败: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 628, in process_segment
    return process_by_llm(asr_data_part.segments, model=model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 587, in process_by_llm
    merged_segments = merge_segments_based_on_sentences(segments, sentences)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 166, in merge_segments_based_on_sentences
    split_segs = split_long_segment(group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 263, in split_long_segment
    result_segs.extend(split_long_segment(second_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 223, in split_long_segment
    max_word_count = MAX_WORD_COUNT_CJK if is_mainly_cjk(merged_text) else MAX_WORD_COUNT_ENGLISH
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 201, in is_mainly_cjk
    cjk_count += len(re.findall(pattern, text))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 216, in findall
  File "re\__init__.py", line 274, in _compile
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\thread\subtitle_optimization_thread.py", line 124, in run
    asr_data = merge_segments(asr_data, model=llm_model,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 634, in merge_segments
    processed_segments = list(executor.map(process_segment, asr_data_segments))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 631, in process_segment
    return process_by_rules(asr_data_part.segments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 561, in process_by_rules
    result_segments.extend(split_long_segment(group))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 985 more times]
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 223, in split_long_segment
    max_word_count = MAX_WORD_COUNT_CJK if is_mainly_cjk(merged_text) else MAX_WORD_COUNT_ENGLISH
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 201, in is_mainly_cjk
    cjk_count += len(re.findall(pattern, text))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 216, in findall
  File "re\__init__.py", line 274, in _compile
RecursionError: maximum recursion depth exceeded while calling a Python object
2024-12-20 17:17:37 - subtitle_optimization_thread - ERROR - 优化失败: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 628, in process_segment
    return process_by_llm(asr_data_part.segments, model=model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 587, in process_by_llm
    merged_segments = merge_segments_based_on_sentences(segments, sentences)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 166, in merge_segments_based_on_sentences
    split_segs = split_long_segment(group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 263, in split_long_segment
    result_segs.extend(split_long_segment(second_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 223, in split_long_segment
    max_word_count = MAX_WORD_COUNT_CJK if is_mainly_cjk(merged_text) else MAX_WORD_COUNT_ENGLISH
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 201, in is_mainly_cjk
    cjk_count += len(re.findall(pattern, text))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 216, in findall
  File "re\__init__.py", line 274, in _compile
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\thread\subtitle_optimization_thread.py", line 124, in run
    asr_data = merge_segments(asr_data, model=llm_model,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 634, in merge_segments
    processed_segments = list(executor.map(process_segment, asr_data_segments))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 631, in process_segment
    return process_by_rules(asr_data_part.segments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 561, in process_by_rules
    result_segments.extend(split_long_segment(group))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 262, in split_long_segment
    result_segs.extend(split_long_segment(first_segs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 985 more times]
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 223, in split_long_segment
    max_word_count = MAX_WORD_COUNT_CJK if is_mainly_cjk(merged_text) else MAX_WORD_COUNT_ENGLISH
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 201, in is_mainly_cjk
    cjk_count += len(re.findall(pattern, text))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 216, in findall
  File "re\__init__.py", line 274, in _compile
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by WEIFENG2333** [comment]
感谢提供详细的日志反馈，已经初步定位问题，下版本会修复这个问题。

**Comment by JockeyW** [comment]
> 感谢提供详细的日志反馈，已经初步定位问题，下版本会修复这个问题。

昨天大半夜收到邮件还很惊讶哈哈哈，竟然真的有bug不是我视频长度的问题，能帮助作者就好

**Comment by blackchicken20** [comment]
> 感谢提供详细的日志反馈，已经初步定位问题，下版本会修复这个问题。

礼貌询问，下个版本大概在什么时候？

从b站看到一些up主的推荐过来的，辛苦跑了三四个小时的视频最后没法优化，心里有点难受。

**Comment by WEIFENG2333** [comment]
问题应该已经修复了，等新版本推送可以下载。
