### ISSUE TITLE
运行出错，程序会停在某个进度

### ISSUE THREAD

**Issue by haiwang08** [WEIFENG2333/VideoCaptioner#180]
### 问题描述 | Problem Description

求助，视频缩短成20分钟左右依然报错，导出成音频再处理依然不行，模型用的是WhisperCPP small

### 日志信息（可选）| Logs (Optional)

```shell
raise RuntimeError(f"WhisperCPP 执行失败: {stderr}")
RuntimeError: WhisperCPP 执行失败: Using GPU "NVIDIA GeForce RTX 4070 Laptop GPU", feature level 12.1, effective flags Wave32 | NoReshapedMatMul
Loaded MEL filters, 62.8 kb RAM
Loaded vocabulary, 51865 strings, 3037.1 kb RAM
Loaded 479 GPU tensors, 464.445 MB VRAM
Computed CPU base frequency: 3.59319 GHz
Loaded model from "C:\Users\rainm\AppData\Local\VideoCaptioner\AppData\models\ggml-small.bin" to VRAM
Created source reader from the file "C:\Users\rainm\AppData\Local\Temp\bk_asr\tmpz9667jtd\audio.wav"
```

**Comment by WEIFENG2333** [comment]
使用的那个WhisperCPP的作者一年多没更新了，确实偶尔会存在这个问题。

建议使用稳定且质量效果更优的的FasterWhisper。

**Comment by haiwang08** [comment]
感谢回复。用FasterWhisper的话会直接报错，日志如下：


[PYI-15980:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2024-12-21 16:18:14 - faster_whisper - ERROR - Faster Whisper 错误: 
2024-12-21 16:18:14 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
    raise RuntimeError(error_msg)
RuntimeError

**Comment by haiwang08** [comment]
> 使用的那个WhisperCPP的作者一年多没更新了，确实偶尔会存在这个问题。
> 
> 你是N卡的话强烈建议使用稳定且质量效果更优的的FasterWhisper。
感谢回复。用FasterWhisper的话会直接报错，模型选largeV2或者tiny都是如此。日志如下：

[PYI-15980:ERROR] Failed to execute script 'main' due to unhandled exception!
Faster Whisper 返回值: 1
2024-12-21 16:18:14 - faster_whisper - ERROR - Faster Whisper 错误:
2024-12-21 16:18:14 - transcript_thread - ERROR - 转录过程中发生错误:
Traceback (most recent call last):
File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
asr_data = self.asr.run(callback=self.progress_callback)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
resp_data = self._run(callback, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
raise RuntimeError(error_msg)
RuntimeError

**Comment by philpw99** [comment]
出问题的 C:\Users\rainm\AppData\Local\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py
在我那边已经修复好了，你去拿就好
https://github.com/philpw99/VideoCaptioner/

**Comment by haiwang08** [comment]
感谢各位，已经可以正常使用了
