### ISSUE TITLE
空格错误

### ISSUE THREAD

**Issue by OnlyCopi** [WEIFENG2333/VideoCaptioner#182]
### 问题描述 | Problem Description

2024-12-22 20:50:33 - VideoCaptioner - ERROR - Traceback (most recent call last):
  File "E:\tools\VideoCaptioner\runtime\Lib\site-packages\qfluentwidgets\common\style_sheet.py", line 241, in eventFilter
    return super().eventFilter(obj, e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type DirtyStyleSheetWatcher has been deleted

2024-12-22 20:50:33 - VideoCaptioner - ERROR - Traceback (most recent call last):
  File "E:\tools\VideoCaptioner\runtime\Lib\site-packages\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 66, in done
    self.setGraphicsEffect(opacityEffect)
RuntimeError: wrapped C/C++ object of type FasterWhisperDownloadDialog has been deleted

**Comment by OnlyCopi** [comment]
知道错误在哪里了,比如:string .exe ,多了一个空格 导致的.希望下个版本能修复这个问题
