### ISSUE TITLE
请问，这什么原因导致的错误

### ISSUE THREAD

**Issue by carrt123** [WEIFENG2333/VideoCaptioner#195]
### 🤔 问题描述 Problem Description

WebM格式视频，强制使用硬字幕
使用硬字幕
WebM格式视频，使用libvpx-vp9编码器
检查CUDA是否可用
CUDA可用
使用CUDA加速
添加硬字幕执行命令: ffmpeg -hwaccel cuda -i F:\vedio_jianji\pingping\task1.webm -acodec copy -vcodec libvpx-vp9 -preset medium -vf subtitles='C\:/Users/us/AppData/Local/Temp/VideoCaptioner/temp_subtitle.ass' -y F:\vedio_jianji\pingping\【卡卡】task1.webm
视频总时长: 1401.69秒
2024-12-26 12:01:30 - video_utils - ERROR - 视频合成失败， 
2024-12-26 12:01:30 - video_utils - ERROR - 关闭 FFmpeg: 3199971767
Traceback (most recent call last):
  File "F:\VideoCaptioner\app\core\utils\video_utils.py", line 208, in add_subtitles
    raise Exception(return_code)
Exception: 3199971767
2024-12-26 12:01:30 - video_synthesis_thread - ERROR - 视频合成失败: 3199971767
Traceback (most recent call last):
  File "F:\VideoCaptioner\app\core\thread\video_synthesis_thread.py", line 40, in run
    add_subtitles(video_file, result_subtitle_save_path, video_save_path, soft_subtitle=soft_subtitle,
  File "F:\VideoCaptioner\app\core\utils\video_utils.py", line 208, in add_subtitles
    raise Exception(return_code)
Exception: 3199971767

**Comment by WEIFENG2333** [comment]
应该是WebM格式的视频的支持问题，后续会改善。

建议先转换为别的格式处理吧~

**Comment by philpw99** [comment]
根据
https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo
或许把subtitle=sub.ass 换成 ass=sub.ass 会比较容易成功

**Comment by carrt123** [comment]
> 应该是WebM格式的视频的支持问题，后续会改善。
> 
> 建议先转换为别的格式处理吧~

好的谢谢

**Comment by carrt123** [comment]
> 根据 https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo 或许把subtitle=sub.ass 换成 ass=sub.ass 会比较容易成功

好的谢谢
