### ISSUE TITLE
合成硬字幕时报错：69

### ISSUE THREAD

**Issue by hxinchen** [WEIFENG2333/VideoCaptioner#198]
### 问题描述 | Problem Description

![image](https://github.com/user-attachments/assets/0c2908a4-a70d-46a9-a0ba-5a24f52db1f1)
合成硬字幕失败，报错69，字幕文件srt，视频格式mp4，仅添加译文
看日志是添加字幕时出错

### 日志信息（可选）| Logs (Optional)

```shell
===========视频合成任务开始===========
时间：2024-12-26 20:38:36.518755
开始合成视频: E:\github项目\VideoCaptioner\work-dir\“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech\“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech.mp4
使用硬字幕
检查CUDA是否可用
CUDA可用
使用CUDA加速
添加硬字幕执行命令: ffmpeg -hwaccel cuda -i "E:\github项目\VideoCaptioner\work-dir\“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech\“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech.mp4" -acodec copy -vcodec libx264 -preset medium -vf subtitles='C\:/Users/ADMINI~1/AppData/Local/Temp/VideoCaptioner/temp_subtitle.ass' -y "E:\github项目\VideoCaptioner\work-dir\“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech\【卡卡】“YOU HAVE TO TAKE A CHANCE” - Steve Harvey Motivational Speech.mp4"
视频总时长: 10.29秒
2024-12-26 20:38:38 - video_utils - ERROR - 视频合成失败， 
2024-12-26 20:38:38 - video_utils - ERROR - 关闭 FFmpeg: 69
Traceback (most recent call last):
  File "E:\github项目\VideoCaptioner\app\core\utils\video_utils.py", line 208, in add_subtitles
    raise Exception(return_code)
Exception: 69
2024-12-26 20:38:38 - video_synthesis_thread - ERROR - 视频合成失败: 69
Traceback (most recent call last):
  File "E:\github项目\VideoCaptioner\app\core\thread\video_synthesis_thread.py", line 40, in run
    add_subtitles(video_file, result_subtitle_save_path, video_save_path, soft_subtitle=soft_subtitle,
  File "E:\github项目\VideoCaptioner\app\core\utils\video_utils.py", line 208, in add_subtitles
    raise Exception(return_code)
Exception: 69
```

**Comment by WEIFENG2333** [comment]
是不是和你视频有关，该视频可以发来测试一下吗？

**Comment by hxinchen** [comment]
https://github.com/user-attachments/assets/2d7d0af8-628f-4f38-805b-b5344310e440


https://github.com/user-attachments/assets/62859712-3511-4722-9077-2509419670fa

**Comment by philpw99** [comment]
可能是ffmpeg命令行里面的
'C\:/Users/ADMINI~1/AppData/Local/Temp/VideoCaptioner/temp_subtitle.ass'
出错了。应该是C:\User\....
