### ISSUE TITLE
1.1.0 版本安装完成后，打开.exe会弹出错误

### ISSUE THREAD

**Issue by Sweetymeow** [WEIFENG2333/VideoCaptioner#55]
### 问题描述 | Problem Description

1.1.0 版本安装完成后，打开.exe会弹出下面错误信息。本地安装目录没有 AppData / App 等路径

### 日志信息（可选）| Logs (Optional)

```shell
Traceback (most recent call last):
File "«string>", line 39, in ‹module»
File "D:\ Program Files)VideoCaptioner Lpystand
_static.int",
", line 19, in < module>
from app.view.main.
_window import MainWindow
File "«frozen importlib. bootstrap>", line 1176, in _find _and _load File "«frozen importlib. _bootstrap>", line 1147, in _find _and _load _unlocked File "«frozen importlib. _bootstrap»", line 690, in _load _unlocked
File "D:\Program Files)VideoCaptioner\app|view\main_window.py", line 10, in < module app.view.main_window>
File "«frozen importlib. _bootstrap>", line 1176, in _find _and _load File "«frozen importlib. _bootstrap>", line 1147, in _find _and _load_unlocked File "«frozen importlib._bootstrap»", line 690, in _load _unlocked
File "D:\Program
Files\VideoCaptioner\app|core\thread\version_manager_thread.py", line 20, in < module app.core.thread.version_manager_thread>
File "D:(Program Files\VideoCaptioner\app|core\utils\logger.py*, line 55, in setup_logger
File "logging\handlers.py", line 155, in init File "logging\handlers.py", line 58, in init File "logging Linit_.py",
", line 1181, in init
File "logging_init_py",
", line 1213, in _open
PermissionError: [Errno 13] Permission denied: 'D:)(Program
Files)\VideoCaptioner\\AppData\\/ogs\\app.log'
```

**Comment by heragehome** [comment]
建议路径
C:\Users\username\AppData\Local\Programs\VideoCaptioner
或以管理员身份运行建议路径
