### ISSUE TITLE
Error Traceback (most recent call last): File "pathlib.py", line 1116, in mkdir FileNotFoundError［WinError 3］系統找不到指定的路径。：'C.\Program Files]\VideoCaptioner\\AppData)(cache'

### ISSUE THREAD

**Issue by Benbenben999** [WEIFENG2333/VideoCaptioner#56]
### 问题描述 | Problem Description

Error
Traceback (most recent call last):
File "pathlib.py", line 1116, in mkdir
FileNotFoundError［WinError 3］系統找不到指定的路径。：'C.\Program
Files]\VideoCaptioner\\AppData)(cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File " «string>*, line 39, in <module>
File "C:\Program Files) VideoCaptioner _pystand static.int", line 18, in < module> from app.common.config import cfg
File "< frozen importlib._bootstrap»", line 1176, in _find _and_load File "«frozen importlib._bootstrap»",
, line 1147, in _find _and _load _unlocked
File "< frozen importlib._bootstrap»", line 690, in _load _unlocked File "C:\Program Files)VideoCaptioner\app\common\config.py",
", line 10, in
«module app.common.config>
File "<frozen importlib._bootstrap»*, line 1176, in _find and _load File "< frozen importlib._bootstrap»", line 1147, in _find _and _load _unlocked File "<frozen importlib._ bootstrap»*, line 690, in _load_unlocked File "C:)Program Files)VideoCaptioner\app\config.py", line 43, in ‹module app.config>
File "pathlib.py", line 1120, in mkdir File "pathlib.py", line 1116, in mkdir
PermissionError. ［WinError 5］拒绝访问。：'C：\\Program
Files)\VideoCaptioner\\AppData'
确定

**Comment by heragehome** [comment]
建议路径
C:\Users\username\AppData\Local\Programs\VideoCaptioner
或以管理员身份运行建议路径

**Comment by WEIFENG2333** [comment]
新版本已经修复权限问题，卸载后安装最新版本即可。
