### ISSUE TITLE
字幕翻译时出现了一个变量错误，希望您排查一下

### ISSUE THREAD

**Issue by puyuanlee** [WEIFENG2333/VideoCaptioner#71]
### 问题描述 | Problem Description

具体报错信息如下：cannot access local variable‘eng_seg_index’ where it is not associated with a value，应该是局部变量和全局变量的设置问题

**Comment by WEIFENG2333** [comment]
可以查看软件安装目录 AppData/log 里面的日志，相关的报错部分完整发我吗？

**Comment by puyuanlee** [comment]
===========字幕优化任务开始===========
时间：2024-11-25 21:44:40.003051
使用 hunyuan-turbo 作为LLM模型
正在字幕断句...
根据字数 2119，确定分段数: 5
正在并行请求LLM将每个分段的文本拆分为句子...
从缓存中获取断句结果
分段的句子提取完成，共 1 句
从缓存中获取断句结果
分段的句子提取完成，共 66 句
从缓存中获取断句结果
分段的句子提取完成，共 1 句
从缓存中获取断句结果
分段的句子提取完成，共 118 句
总共提取到 186 句
正在合并ASR分段基于句子列表...
2024-11-25 21:44:41 - subtitle_spliter - WARNING - 无法匹配句子: さあ
2024-11-25 21:44:41 - subtitle_optimization_thread - ERROR - 优化失败: cannot access local variable 'end_seg_index' where it is not associated with a value
Traceback (most recent call last):
  File "D:\Program Files (x86)\VideoCaptioner\app\core\thread\subtitle_optimization_thread.py", line 123, in run
  File "D:\Program Files (x86)\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 362, in merge_segments
  File "D:\Program Files (x86)\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 153, in merge_segments_based_on_sentences
UnboundLocalError: cannot access local variable 'end_seg_index' where it is not associated with a value

**Comment by puyuanlee** [comment]
> 可以查看软件安装目录 AppData/log 里面的日志，相关的报错部分完整发我吗？
===========字幕优化任务开始===========
时间：2024-11-25 21:44:40.003051
使用 hunyuan-turbo 作为LLM模型
正在字幕断句...
根据字数 2119，确定分段数: 5
正在并行请求LLM将每个分段的文本拆分为句子...
从缓存中获取断句结果
分段的句子提取完成，共 1 句
从缓存中获取断句结果
分段的句子提取完成，共 66 句
从缓存中获取断句结果
分段的句子提取完成，共 1 句
从缓存中获取断句结果
分段的句子提取完成，共 118 句
总共提取到 186 句
正在合并ASR分段基于句子列表...
2024-11-25 21:44:41 - subtitle_spliter - WARNING - 无法匹配句子: さあ
2024-11-25 21:44:41 - subtitle_optimization_thread - ERROR - 优化失败: cannot access local variable 'end_seg_index' where it is not associated with a value
Traceback (most recent call last):
  File "D:\Program Files (x86)\VideoCaptioner\app\core\thread\subtitle_optimization_thread.py", line 123, in run
  File "D:\Program Files (x86)\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 362, in merge_segments
  File "D:\Program Files (x86)\VideoCaptioner\app\core\subtitle_processor\spliter.py", line 153, in merge_segments_based_on_sentences
UnboundLocalError: cannot access local variable 'end_seg_index' where it is not associated with a value
