### ISSUE TITLE
语音转录时会卡住，圆圈进度条始终停留在1/4，右侧“开始转录”按钮，也没有变成进度，而是一直显示为whisper识别

### ISSUE THREAD

**Issue by Soracoogroo** [WEIFENG2333/VideoCaptioner#84]
### 问题描述 | Problem Description

还有个问题，语音转录时会卡住，圆圈进度条始终停留在1/4，右侧“开始转录”按钮，也没有变成进度，而是一直显示为whisper识别，同时gpu也没有调用，gpu占用很低0%

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：2024-11-27 23:00:39.162756
开始转换音频
开始语音转录
找到模型文件: E:\Program Files\VideoCaptioner\AppData\models\ggml-large-v3.bin
WhisperCPP 执行命令: whisper-cpp -m E:\Program Files\VideoCaptioner\AppData\models\ggml-large-v3.bin C:\Users\Sora\AppData\Local\Temp\bk_asr\20241127230039aaaa-a.wav -l ja -osrt
音频总时长: 6852 秒
```

**Comment by WEIFENG2333** [comment]
不要使用v3，readme已经说明了。

**Comment by Soracoogroo** [comment]
OK，更新版本就没看readme。。。看到有v3就准备试试，结果就不行了，谢谢解答。

**Comment by 1379733** [comment]
您好，我也有这样的问题，我用cpu就可以转录，用gpu就一直转录失败，用的V2的模型

日志信息
```
===========转录任务开始===========
时间：2025-05-17 11:07:50.331179
开始转换音频
转换为音频执行命令: ffmpeg -i E:\BaiduNetdiskDownload\4月11日.MP3 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y C:\Users\MUZHI\AppData\Local\Temp\tmpc6vyoj6d.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl -m large-v2 --print_progress --model_dir D:\VideoCaptioner\AppData\models C:\Users\MUZHI\AppData\Local\Temp\bk_asr\tmpzww2wl6r\audio.wav -l zh -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v4 --one_word 0 --sentence --max_line_width 30 --max_line_count 1 --max_comma 20 --max_comma_cent 50 --beep_off
Standalone Faster-Whisper-XXL r245.2 running on: CUDA
Starting sequential inference to transcribe: C:\Users\MUZHI\AppData\Local\Temp\bk_asr\tmpzww2wl6r\audio.wav
Traceback (most recent call last):
File "D:\whisper-fast-XXL\__main__.py", line 2245, in <module>
File "D:\whisper-fast-XXL\__main__.py", line 2118, in cli
File "faster_whisper\transcribe.py", line 2179, in restore_speech_timestamps
File "faster_whisper\transcribe.py", line 1471, in generate_segments
File "faster_whisper\transcribe.py", line 1719, in encode
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
[PYI-19452:ERROR] Failed to execute script '__main__' due to unhandled exception!
Faster Whisper 返回值: 1
2025-05-17 11:07:57 - faster_whisper - ERROR - Faster Whisper 错误: 
2025-05-17 11:07:57 - transcript_thread - ERROR - 转录过程中发生错误: 
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\thread\transcript_thread.py", line 101, in run
    asr_data = transcribe(
               ^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\transcribe.py", line 86, in transcribe
    asr_data = asr.run(callback=callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\base.py", line 54, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\faster_whisper.py", line 266, in _run
    raise RuntimeError(error_msg)
RuntimeError
```
